language: ruby

sudo: false
cache: bundler

env:
  global:
    - TRAVIS_CI=1

rvm:
  - 1.9.3
  - 2.3.3

gemfile:
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile

matrix:
  exclude:
  - rvm: 1.9.3
    gemfile: gemfiles/rails_5.0.gemfile

before_install: gem update bundler
bundler_args: --without tools

script: bundle exec rspec -b
